"use strict";var __awaiter=function(a,b,c,d){function e(a){return a instanceof c?a:new c(function(b){b(a)})}return new(c||(c=Promise))(function(c,f){function g(a){try{i(d.next(a))}catch(a){f(a)}}function h(a){try{i(d["throw"](a))}catch(a){f(a)}}function i(a){a.done?c(a.value):e(a.value).then(g,h)}i((d=d.apply(a,b||[])).next())})},__generator=function(a,b){function c(a){return function(b){return d([a,b])}}function d(c){if(e)throw new TypeError("Generator is already executing.");for(;j&&(j=0,c[0]&&(k=0)),k;)try{if(e=1,h&&(i=2&c[0]?h["return"]:c[0]?h["throw"]||((i=h["return"])&&i.call(h),0):h.next)&&!(i=i.call(h,c[1])).done)return i;switch((h=0,i)&&(c=[2&c[0],i.value]),c[0]){case 0:case 1:i=c;break;case 4:return k.label++,{value:c[1],done:!1};case 5:k.label++,h=c[1],c=[0];continue;case 7:c=k.ops.pop(),k.trys.pop();continue;default:if((i=k.trys,!(i=0<i.length&&i[i.length-1]))&&(6===c[0]||2===c[0])){k=0;continue}if(3===c[0]&&(!i||c[1]>i[0]&&c[1]<i[3])){k.label=c[1];break}if(6===c[0]&&k.label<i[1]){k.label=i[1],i=c;break}if(i&&k.label<i[2]){k.label=i[2],k.ops.push(c);break}i[2]&&k.ops.pop(),k.trys.pop();continue}c=b.call(a,k)}catch(a){c=[6,a],h=0}finally{e=i=0}if(5&c[0])throw c[1];return{value:c[0]?c[1]:void 0,done:!0}}var e,h,i,j,k={label:0,sent:function a(){if(1&i[0])throw i[1];return i[1]},trys:[],ops:[]};return j={next:c(0),throw:c(1),return:c(2)},"function"==typeof Symbol&&(j[Symbol.iterator]=function(){return this}),j},__importDefault=function(a){return a&&a.__esModule?a:{default:a}};Object.defineProperty(exports,"__esModule",{value:!0}),exports.decryptSignedKey=exports.encryptKey=void 0;var ali_oss_1=__importDefault(require("ali-oss")),crypto_1=__importDefault(require("crypto")),path_1=__importDefault(require("path")),fs_1=__importDefault(require("fs")),fs_extra_1=__importDefault(require("fs-extra")),chalk_1=__importDefault(require("chalk")),process_1=__importDefault(require("process")),draftlog_1=__importDefault(require("draftlog"));draftlog_1.default.into(console);var envs=["prd","test"],uploadAliOss=function d(a,b,c){return __awaiter(void 0,void 0,void 0,function(){function d(a,b){return __awaiter(this,void 0,void 0,function(){var c;return __generator(this,function(d){switch(d.label){case 0:return d.trys.push([0,2,,3]),o++,[4/*yield*/,n.put(a,b)];case 1:return d.sent(),o--,[3/*break*/,3];case 2:return c=d.sent(),g(c),[3/*break*/,3];case 3:return[2/*return*/]}})})}// put all files/dirs under dist to ossPath
function e(a,b){fs_1.default.readdirSync(a).forEach(function(c){var f=path_1.default.join(a,c),g=fs_1.default.lstatSync(f);g.isFile()?d("".concat(b).concat(c),f):g.isDirectory()&&e(f,"".concat(b).concat(c,"/"))})}function f(a){return q=(q+1)%r.length,chalk_1.default.green(r[q])+" "+chalk_1.default.green(a)}function g(a){console.log(chalk_1.default.red(a)),process_1.default.exit(9)}function h(){var a=fs_1.default.rmSync?fs_1.default.rmSync:fs_1.default.rmdirSync;a(path_1.default.resolve(process_1.default.cwd(),"./".concat(i[c])),{recursive:!0})}var i,j,k,l,m,n,o,p,q,r,s,u;return __generator(this,function(d){return i={test:"t-dist",prd:"dist"},c||g("env is required"),-1===envs.indexOf(c)&&g("env must be prd,test"),fs_extra_1.default.pathExistsSync(path_1.default.resolve(process_1.default.cwd(),i[c]))||g("dist not exit"),j=a.region,k=a.accessKeyId,l=a.accessKeySecret,m=a.bucket,n=new ali_oss_1.default({region:j,accessKeyId:k,accessKeySecret:l,bucket:m}),o=0,p=path_1.default.resolve(process_1.default.cwd(),"./".concat(i[c],"/")),e(p,"".concat(c,"/").concat(b,"/")),q=0,r=["-","\\","|","/"],s=console.draft(),u=function a(){0===o?(console.log(chalk_1.default.green("".concat("prd"===c?"production":"non-production"," uploaded"))),h()):(s(f("oss uploading...")),setTimeout(u,60))},u(),[2/*return*/]})})},key="9vApxLk5G3PAsJXM",iv="FnJL7EDzjqWjcaX9";/**
 * encrypt a key
 * @param src
 * @returns
 */function encryptKey(a){var b="",c=crypto_1.default.createCipheriv("aes-128-cbc",key,iv);return b+=c.update(a,"utf8","hex"),b+=c.final("hex"),b}exports.encryptKey=encryptKey;/**
 * decrypt a signed key
 * @param sign
 * @returns
 */function decryptSignedKey(a){var b="",c=crypto_1.default.createDecipheriv("aes-128-cbc",key,iv);return b+=c.update(a,"hex","utf8"),b+=c.final("utf8"),b}exports.decryptSignedKey=decryptSignedKey,exports.default=uploadAliOss;